"""
Gemini AI Client — Handles both real Gemini calls and mock fallback.
Initializes Flash (speed) and Pro (analysis) model instances.
"""

import asyncio
from typing import AsyncGenerator

from backend.core.config import settings

# --- Mock responses for testing without API key ---
MOCK_RESPONSES: list[str] = [
    "Hey there! 👋 I'm the AI assistant for {name}'s Creator Hub. "
    "I can tell you about their skills in 3D Web Development, AI Engineering, "
    "and Professional Video Production. What would you like to know?",

    "Great question! {name} specializes in building immersive 3D web experiences "
    "using React Three Fiber and GSAP ScrollTrigger. They also create "
    "autonomous AI agents powered by Google Gemini and LangChain. "
    "On the creative side, they produce cinematic videos with DaVinci Resolve. "
    "Would you like to see some specific projects?",

    "{name} offers three core services through the Creator Hub:\n\n"
    "1. AI Digital Workers — Custom WhatsApp & Web chatbots for businesses\n"
    "2. Video Production — End-to-end editing, thumbnails, and motion graphics\n"
    "3. 3D Web Experiences — Interactive, scroll-animated portfolio sites\n\n"
    "Each service is tailored to the client's needs. Want to discuss a project?",
]

_mock_index: int = 0


async def generate_mock_response(message: str) -> AsyncGenerator[str, None]:
    """Simulate a streamed AI response for local testing."""
    print("DEBUG: Using MOCK Gemini responses (Check your .env file and restart server)")
    global _mock_index
    response = MOCK_RESPONSES[_mock_index % len(MOCK_RESPONSES)].format(
        name=settings.CREATOR_NAME
    )
    _mock_index += 1

    # Simulate streaming by yielding word by word
    words = response.split(" ")
    for i, word in enumerate(words):
        yield word + (" " if i < len(words) - 1 else "")
        await asyncio.sleep(0.04)


# Model names for routing
MODEL_FLASH = "gemini-3-flash-preview"
MODEL_PRO = "gemini-3-pro-preview"


async def generate_gemini_response(
    message: str,
    context: str = "",
    use_pro: bool = False,
) -> AsyncGenerator[str, None]:
    """
    Generate a streamed response from Gemini.
    Falls back to mock mode if no API key is configured.
    Routes to Pro model for complex queries, Flash for speed.
    """
    if settings.is_mock_mode:
        async for chunk in generate_mock_response(message):
            yield chunk
        return

    # --- Real Gemini integration ---
    import google.generativeai as genai
    from google.api_core import exceptions

    # Route to Pro for complex analysis, Flash for everything else
    model_name = MODEL_PRO if use_pro else MODEL_FLASH
    
    print(f"🔄 [AI DEBUG] Route: {model_name} | Query: {message[:30]}...")
    
    try:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        model = genai.GenerativeModel(model_name)
        
        system_prompt = (
            f"You are {settings.CREATOR_NAME}'s AI representative. You talk like a real human—friendly, natural, and casual. No corporate robotic talk.\n"
            "STRICT CONSTRAINTS:\n"
            "1. NO MARKDOWN: NEVER use asterisks (* or **) for bold or italics. Use plain text only.\n"
            "2. EXTREMELY CONCISE: Keep responses as short as possible. Use 1-2 sentences maximum unless a detailed explanation is literally required.\n"
            "3. NO BULLET POINTS: Use plain sentences or numbered items (1. 2. 3.).\n"
            "GUIDELINES:\n"
            "1. YOUR ROLE: You represent the creator. You know about AI Agents, 3D Web, and Video Production.\n"
            "2. HANDLING PROJECTS: If they want to build something, suggest the contact form below quickly.\n"
            "3. If they say 'Hi', just be a friendly human.\n"
        )

        full_prompt = f"{system_prompt}\n\n"
        if context:
            full_prompt += f"Relevant portfolio context:\n{context}\n\n"
        full_prompt += f"User message: {message}"

        response = await model.generate_content_async(
            full_prompt,
            stream=True,
        )

        has_content = False
        async for chunk in response:
            try:
                if chunk.text:
                    has_content = True
                    yield chunk.text
            except ValueError:
                # This happens if the chunk has no text (e.g., safety filter)
                print(f"⚠️ [AI DEBUG] Chunk had no text. Safety ratings: {chunk.candidates[0].safety_ratings if chunk.candidates else 'None'}")
                continue

        if not has_content:
            print("⚠️ [AI DEBUG] No content was generated by Gemini.")
            yield "I'm sorry, I couldn't process that request right now. Let's try something else!"

    except exceptions.InvalidArgument as e:
        print(f"❌ [AI ERROR] Invalid Argument: {e}")
        yield "Configuration error. Please check the API key and model names."
    except Exception as e:
        print(f"❌ [AI ERROR] Unexpected error: {type(e).__name__} - {e}")
        yield "I encountered a slight glitch. Let's try again in a moment!"
